//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceMaster
    {
        public AllowanceMaster()
        {
            this.EmployeeAllowanceMaps = new HashSet<EmployeeAllowanceMap>();
        }
    
        public System.Guid AllowanceID { get; set; }
        public string Allowance { get; set; }
        public bool IsConsider { get; set; }
        public int SortNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<double> Percentage { get; set; }
    
        public virtual ICollection<EmployeeAllowanceMap> EmployeeAllowanceMaps { get; set; }
    }
}
