//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMaster
    {
        public System.Guid CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyLogo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<System.Guid> StateId { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string HotlineNo { get; set; }
        public string FaxNo { get; set; }
        public string Website { get; set; }
        public string LicenseKey { get; set; }
        public Nullable<bool> IsKeyActive { get; set; }
        public string TINNo { get; set; }
        public string BusinessPermitNo { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string Remarks { get; set; }
    }
}
