//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyMaster
    {
        public CurrencyMaster()
        {
            this.InvoiceMasters = new HashSet<InvoiceMaster>();
        }
    
        public int CurrencyID { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<InvoiceMaster> InvoiceMasters { get; set; }
    }
}
