//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTRRaw
    {
        public System.Guid DTRRawId { get; set; }
        public Nullable<System.Guid> CutOffId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string StaffCode { get; set; }
        public string TimeType { get; set; }
        public Nullable<int> TimeTypeOrder { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<System.TimeSpan> ActualTime { get; set; }
        public string FromType { get; set; }
        public Nullable<int> RawOrder { get; set; }
    }
}
