//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public System.Guid EmployeeAttendanceID { get; set; }
        public Nullable<System.Guid> FinancialYearId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public Nullable<decimal> WorkingHours { get; set; }
        public Nullable<decimal> OverTimeHours { get; set; }
        public Nullable<int> AttendanceType { get; set; }
        public Nullable<decimal> Attendance { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
    }
}
