//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveCategory
    {
        public System.Guid EmployeeLeaveCategoryMapID { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid LeaveCategoryId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalDay { get; set; }
        public bool IsFirstHalfDay { get; set; }
        public bool IsLastHalfDay { get; set; }
        public string Reason { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsApprove { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual LeaveCategoryMaster LeaveCategoryMaster { get; set; }
    }
}
