//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLoan
    {
        public EmployeeLoan()
        {
            this.EmployeePaidLoans = new HashSet<EmployeePaidLoan>();
        }
    
        public System.Guid EmployeeLoanMapID { get; set; }
        public System.Guid EmployeeId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime LoanDate { get; set; }
        public string LoanTitle { get; set; }
        public string Description { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> TotalMonths { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsComplete { get; set; }
    
        public virtual ICollection<EmployeePaidLoan> EmployeePaidLoans { get; set; }
        public virtual EmployeeMaster EmployeeMaster { get; set; }
    }
}
