//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfile
    {
        public EmployeeProfile()
        {
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public System.Guid EmployeeId { get; set; }
        public string PicImg { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string MartialStatus { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<decimal> NoOfChildren { get; set; }
        public Nullable<decimal> CurrentBasicPay { get; set; }
        public string PaymentTerms { get; set; }
        public string EmploymentStatus { get; set; }
        public string HouseStreetNo { get; set; }
        public string BarangayTownVillage { get; set; }
        public string CityMunicipalityProvince { get; set; }
        public Nullable<System.Guid> County { get; set; }
        public Nullable<System.Guid> Region { get; set; }
        public string PostalCode { get; set; }
        public string HomeTelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddress { get; set; }
        public string HighEducAttainment { get; set; }
        public string School { get; set; }
        public string YearsCompleted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string ContractType { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.Guid> DesignationId { get; set; }
        public Nullable<System.Guid> WorkLocationId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string CostCenter { get; set; }
        public string TypeOfNCR { get; set; }
        public string TINNo { get; set; }
        public string TaxExemption { get; set; }
        public string SSSNo { get; set; }
        public string PagIbigNo { get; set; }
        public string PhilhealthNo { get; set; }
        public string DriverLicenseNo { get; set; }
        public string StaffCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsResigned { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
    
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
