//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePaidLoan
    {
        public System.Guid EmployeePaidLoanMapID { get; set; }
        public System.Guid EmployeeLoanMapId { get; set; }
        public decimal PaidAmount { get; set; }
        public System.DateTime PaidDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
    
        public virtual EmployeeLoan EmployeeLoan { get; set; }
    }
}
