//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMaster
    {
        public FieldMaster()
        {
            this.ValueMasters = new HashSet<ValueMaster>();
        }
    
        public System.Guid FieldId { get; set; }
        public Nullable<System.Guid> FormId { get; set; }
        public string FieldLabel { get; set; }
        public string FieldType { get; set; }
        public Nullable<bool> FieldIsRequired { get; set; }
        public string ItemsJson { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual FormMaster FormMaster { get; set; }
        public virtual ICollection<ValueMaster> ValueMasters { get; set; }
    }
}
