//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialYearMaster
    {
        public FinancialYearMaster()
        {
            this.EmployeePaidSalaries = new HashSet<EmployeePaidSalary>();
        }
    
        public System.Guid FinancialYearID { get; set; }
        public int Year { get; set; }
        public string FinancialYear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public Nullable<System.Guid> LockedBy { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    
        public virtual ICollection<EmployeePaidSalary> EmployeePaidSalaries { get; set; }
    }
}
