//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormMaster
    {
        public FormMaster()
        {
            this.FieldMasters = new HashSet<FieldMaster>();
        }
    
        public System.Guid FormId { get; set; }
        public string FormName { get; set; }
        public string FormType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string JsonData { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<FieldMaster> FieldMasters { get; set; }
    }
}
