//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSetting
    {
        public int GlobalSettingId { get; set; }
        public string GlobalSettingName { get; set; }
        public string GlobalSettingEnum { get; set; }
        public string GlobalSettingValue { get; set; }
    }
}
