//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewMaster
    {
        public InterviewMaster()
        {
            this.InterviewAttachments = new HashSet<InterviewAttachment>();
        }
    
        public System.Guid InterviewID { get; set; }
        public int InterviewNo { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public System.Guid EducationId { get; set; }
        public System.Guid DepartmentId { get; set; }
        public System.Guid DesignationId { get; set; }
        public Nullable<decimal> CurrentSalary { get; set; }
        public Nullable<decimal> ExpectedSalary { get; set; }
        public Nullable<int> ExperienceYear { get; set; }
        public Nullable<int> ExperienceMonth { get; set; }
        public Nullable<bool> IsJoinDays { get; set; }
        public Nullable<int> JoinAfterDaysOrMonth { get; set; }
        public string PersonalDetail { get; set; }
        public Nullable<int> InterviewStatusId { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string InterviewTime { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual EducationMaster EducationMaster { get; set; }
        public virtual ICollection<InterviewAttachment> InterviewAttachments { get; set; }
    }
}
