//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMaster
    {
        public InvoiceMaster()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int InvoiceID { get; set; }
        public int InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string PartyName { get; set; }
        public string PartyAddress { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> SubTotalINR { get; set; }
        public Nullable<decimal> ServiceTaxINR { get; set; }
        public Nullable<decimal> GrandTotalINR { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CurrencyMaster CurrencyMaster { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
