//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpInformation
    {
        public System.Guid Id { get; set; }
        public string IpAddress { get; set; }
        public string DeviceName { get; set; }
        public string BrowserName { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
