//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCategoryMaster
    {
        public LeaveCategoryMaster()
        {
            this.EmployeeLeaveCategories = new HashSet<EmployeeLeaveCategory>();
        }
    
        public System.Guid LeaveCategoryID { get; set; }
        public string LeaveCategory { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EmployeeLeaveCategory> EmployeeLeaveCategories { get; set; }
    }
}
