//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        public ModuleMaster()
        {
            this.UserModuleMaps = new HashSet<UserModuleMap>();
        }
    
        public System.Guid ModuleID { get; set; }
        public string EnumName { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int TreeLevel { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<UserModuleMap> UserModuleMaps { get; set; }
    }
}
