//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollCutOffMaster
    {
        public PayrollCutOffMaster()
        {
            this.PayrollMasters = new HashSet<PayrollMaster>();
        }
    
        public System.Guid PayrollCutOffId { get; set; }
        public string CutOffCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime ActualDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatedById { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public Nullable<System.Guid> LockedById { get; set; }
    
        public virtual ICollection<PayrollMaster> PayrollMasters { get; set; }
    }
}
