//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollSummary
    {
        public System.Guid PayrollTimeId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid PayrollId { get; set; }
        public Nullable<System.Guid> WorkLocationId { get; set; }
        public Nullable<decimal> gMonthlyRate { get; set; }
        public Nullable<decimal> gHalfMonthEarning { get; set; }
        public Nullable<decimal> gRTDays { get; set; }
        public Nullable<decimal> gRTHrs { get; set; }
        public Nullable<decimal> gdAbsDay { get; set; }
        public Nullable<decimal> dAbsHrs { get; set; }
        public Nullable<decimal> gRTOTHrs { get; set; }
        public Nullable<decimal> gRTOTAmt { get; set; }
        public Nullable<decimal> gRDHrs { get; set; }
        public Nullable<decimal> gRDAmt { get; set; }
        public Nullable<decimal> gSHHrs { get; set; }
        public Nullable<decimal> gSHAmt { get; set; }
        public Nullable<decimal> gPosAllowance { get; set; }
        public Nullable<decimal> gSIL { get; set; }
        public Nullable<decimal> gAdjAmt { get; set; }
        public Nullable<decimal> gAdjustmentDays { get; set; }
        public Nullable<decimal> g30PerOT { get; set; }
        public Nullable<decimal> dCigna { get; set; }
        public Nullable<decimal> dPhicPrem { get; set; }
        public Nullable<decimal> dHDMF { get; set; }
        public Nullable<decimal> dHDMFLoan { get; set; }
        public Nullable<decimal> dMotorLoan { get; set; }
        public Nullable<decimal> dCashAdv { get; set; }
        public Nullable<decimal> dSplFunds { get; set; }
        public Nullable<decimal> TtlDeduction { get; set; }
        public Nullable<decimal> TtlNetSalary { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<decimal> NoofDays { get; set; }
        public Nullable<decimal> TotalBasic { get; set; }
        public Nullable<decimal> gNP1Hrs { get; set; }
        public Nullable<decimal> gNP1Amt { get; set; }
        public Nullable<decimal> gNP2Hrs { get; set; }
        public Nullable<decimal> gNP2Amt { get; set; }
        public Nullable<decimal> gNP3Hrs { get; set; }
        public Nullable<decimal> gNP3Amt { get; set; }
        public Nullable<decimal> gNP4Hrs { get; set; }
        public Nullable<decimal> gNP4Amt { get; set; }
        public Nullable<decimal> ttlGross { get; set; }
    }
}
