//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollDTR
    {
        public System.Guid DTRId { get; set; }
        public System.Guid PayrollCutOffId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public Nullable<System.Guid> ScheduleId { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<decimal> WorkingHrs { get; set; }
        public Nullable<decimal> LateHrs { get; set; }
        public Nullable<decimal> OvertimeHrs { get; set; }
        public Nullable<decimal> AdjustHrs { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.TimeSpan> timein { get; set; }
        public Nullable<System.TimeSpan> timeout { get; set; }
        public string status { get; set; }
    }
}
