//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMaster
    {
        public System.Guid PayrollId { get; set; }
        public string PayrollCode { get; set; }
        public Nullable<System.Guid> WorkLocationId { get; set; }
        public Nullable<System.Guid> CutOffId { get; set; }
        public string PaymentTerms { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> IsLockedDTR { get; set; }
        public Nullable<System.DateTime> LockedDTRDate { get; set; }
        public Nullable<System.Guid> LockedDTRBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<bool> IsLockedPTSR { get; set; }
        public Nullable<System.DateTime> LockedPTSRDate { get; set; }
        public Nullable<System.Guid> LockedPTSRBy { get; set; }
        public Nullable<bool> IsBankFileGenerated { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public Nullable<System.Guid> GeneratedBy { get; set; }
        public string BankType { get; set; }
        public Nullable<System.Guid> BankFileId { get; set; }
        public Nullable<decimal> TotalWorks { get; set; }
        public Nullable<decimal> TotalEmployee { get; set; }
        public Nullable<decimal> TotalDeduction { get; set; }
        public Nullable<decimal> TotalSSS { get; set; }
        public Nullable<decimal> TotalPHIC { get; set; }
        public Nullable<decimal> TotalHDMF { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
    
        public virtual PayrollCutOffMaster PayrollCutOffMaster { get; set; }
    }
}
