//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLogEntry
    {
        public System.Guid TimelogId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public Nullable<System.DateTime> EntryLog { get; set; }
        public string EntryType { get; set; }
    }
}
