//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimelogSummary
    {
        public System.Guid TimelogId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public Nullable<System.DateTime> logindate { get; set; }
        public Nullable<System.TimeSpan> logintime { get; set; }
        public Nullable<System.DateTime> breakindate { get; set; }
        public Nullable<System.TimeSpan> breakintime { get; set; }
        public Nullable<System.DateTime> breakoutdate { get; set; }
        public Nullable<System.TimeSpan> breakouttime { get; set; }
        public Nullable<System.DateTime> overindate { get; set; }
        public Nullable<System.TimeSpan> overintime { get; set; }
        public Nullable<System.DateTime> overoutdate { get; set; }
        public Nullable<System.TimeSpan> overouttime { get; set; }
        public Nullable<System.DateTime> logoutdate { get; set; }
        public Nullable<System.TimeSpan> logouttime { get; set; }
        public bool isactive { get; set; }
    
        public virtual EmployeeProfile EmployeeProfile { get; set; }
    }
}
