//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserModuleMap
    {
        public System.Guid UserModuleMapID { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ModuleId { get; set; }
    
        public virtual ModuleMaster ModuleMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
