//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.UserModuleMaps = new HashSet<UserModuleMap>();
        }
    
        public System.Guid UserID { get; set; }
        public System.Guid RoleId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual EmployeeMaster EmployeeMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual ICollection<UserModuleMap> UserModuleMaps { get; set; }
    }
}
