//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Common.GlobalMsg", typeof(GlobalMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist, please add another Email..
        /// </summary>
        public static string AlreadyExistKeyMsg {
            get {
                return ResourceManager.GetString("AlreadyExistKeyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name already exist, please add another name..
        /// </summary>
        public static string AlreadyExistMsg {
            get {
                return ResourceManager.GetString("AlreadyExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct username and password..
        /// </summary>
        public static string AuthenticationFailMsg {
            get {
                return ResourceManager.GetString("AuthenticationFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arity Infoway.
        /// </summary>
        public static string CompanyTeamName {
            get {
                return ResourceManager.GetString("CompanyTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        public static string DeletionSuccessMsg {
            get {
                return ResourceManager.GetString("DeletionSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again or Contact to support team..
        /// </summary>
        public static string ExceptionErrMsg {
            get {
                return ResourceManager.GetString("ExceptionErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string NoRecordFoundMsg {
            get {
                return ResourceManager.GetString("NoRecordFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password do not match current password. Please enter correct password..
        /// </summary>
        public static string OldPasswordNotMatchMsg {
            get {
                return ResourceManager.GetString("OldPasswordNotMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reference used in another place, you cannot perform delete action..
        /// </summary>
        public static string ReferenceExistMsg {
            get {
                return ResourceManager.GetString("ReferenceExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been saved successfully..
        /// </summary>
        public static string SaveSuccessMsg {
            get {
                return ResourceManager.GetString("SaveSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send the e-mail because your network problem. Please try again!.
        /// </summary>
        public static string SendFailMsg {
            get {
                return ResourceManager.GetString("SendFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great. We have sent reset password link in your email..
        /// </summary>
        public static string SendLinkSuccessMsg {
            get {
                return ResourceManager.GetString("SendLinkSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email send successfully. .
        /// </summary>
        public static string SendSuccessMsg {
            get {
                return ResourceManager.GetString("SendSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username does not exist. Please enter correct username..
        /// </summary>
        public static string UsernameNotExistsMsg {
            get {
                return ResourceManager.GetString("UsernameNotExistsMsg", resourceCulture);
            }
        }
    }
}
